id: setup_docker_skills_selection
hints: []
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
        - text: "Ok! It's time for your first official task, and I want to make sure it's a good one!"
          delay: 2000
        - text: "For that, I need to know **what areas and skills you'd like to focus on,** in your journey with us."
          delay: 2000
        - components:
            - type: form
              form:
                id: skill_selection
                type: multi_select_form
                randomized: true
                select_limit: 3
                action_label: 'Submit Selection'
                options:
                  - text: 'setup'
                  - text: 'observability'
                  - text: 'debugging'
                  - text: 'communication'
                  - text: 'documentation'
                  - text: 'monitoring'
                  - text: 'operations'
                  - text: 'performace'

trigger:
  type: chat_form_submitted
  params:
    formId: skill_selection
  flowNode:
    do:
    - actionId: update_user_props
      params:
        field: "onboarding.skills"
        value: "${{formSubmission}}"
    - actionId: bot_message
      params:
        person: head-of-rd
        messages:
          - text: "You chose well, young grasshopper 🦗✨ "
            delay: 2000
    - actionId: finish_step

