id: setup_docker_create_codespace
learningObjectives:
  - Setting up Github Codespace
hints:
  - Make sure your Codespace has started and is ready to use.
startFlow:
  do:
    - actionId: bot_message
      params:
        person: head-of-rd
        messages:
          - text: "![](https://media.giphy.com/media/8fen5LSZcHQ5O/giphy.gif)"
            delay: 800
          - text: I bet you’re eager to get your hands dirty. Let’s **set up your development environment** so you can start exploring the system.
            delay:
          - text: At Anythink, our engineers work with [Github Codespaces](https://docs.github.com/en/codespaces/overview), which can be run directly in Github, so you don't need to install anything on your computer!
            delay: 2000
          - text: :Instruction[Go ahead and[ **create your own Codespace**.](https://github.com/codespaces/new?hide_repo_select=true&ref=main&repo=${user.repoId})]{block=true}
            delay: 1300
          - text: You don't need to change anything in the default options, just **click `Create Codespace` and wait a minute or two until it boots up**.
            delay: 2000
          - text: We'll let you know once it's up and running.
            delay: 1000
trigger:
  type: github_codespace_started
  flowNode:
    do:
      - actionId: bot_message
        params:
          person: head-of-rd
          messages:
            - text: "**Amazing! Looks like your codespace is up and running.**"
              delay: 1500
      - actionId: finish_step
