id: setup_docker_skills_selection
hints: []
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
        - text: "Sounds good! **What specific skills do you want to focus on?** (choose up to 3)"
          delay: 2300
        - components:
            - type: form
              form:
                id: skill_selection
                type: multi_select_form
                randomized: true
                select_limit: 3
                action_label: 'Submit Selection'
                options:
                  - value: 'setup'
                    label: 'Setup'
                  - value: 'observability'
                    label: 'Observability'
                  - value: 'debugging'
                    label: 'Debugging'
                  - value: 'communication'
                    label: 'Communication'
                  - value: 'documentation'
                    label: 'Documentation'
                  - value: 'monitoring'
                    label: 'Monitoring'
                  - value: 'operations'
                    label: 'Operations'
                  - value: 'performance'
                    label: 'Performance'

trigger:
  type: chat_form_submitted
  params:
    formId: skill_selection
  flowNode:
    do:
    - actionId: update_user_props
      params:
        field: "onboarding.skills"
        value: "${{formSubmission}}"
    - actionId: bot_message
      params:
        person: head-of-rd
        messages:
          - text: "You chose well, young grasshopper 🦗✨ "
            delay: 2000
    - actionId: finish_step

