id: setup_docker_continue_generic
hints:
- Read through the Docker installation guide thoroughly and make sure you didn't miss
  any steps.
- If you've already installed Docker on your machine, open the application and follow
  the Quick Start Guide. To run the Quick Start Guide on demand, select the Docker
  menu and then choose Quick Start Guide.
- Make sure you ran the \`docker-compose up\` (or \`docker compose up\`) command from the **project root (main) directory**
  and that it finished running. This may take a few minutes.
startFlow:
  if:
    conditions:
    - conditionId: user_has_feature_flag
      params:
        featureFlag: 'codespaces'
    then:
      do:
      - actionId: finish_step
    else: 
      do: 
      - actionId: bot_message
        params:
          person: head-of-rd
          messages:
          - text: I bet you’re eager to get your hands dirty. Let’s set up your local environment so you can start exploring the system.
            delay: 2000
          - text: "**First things first - :codeInstruction[download install Docker](https://docs.docker.com/get-docker/)** and write me back when you're **done**." 
            delay: 5500
trigger:
  type: user_message
  params:
    person: head-of-rd
  flowNode:
    if:
      conditions:
      - conditionId: is_user_message_text_ready_to_continue
      then:
        do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
            - text: Great!
              delay: 1000
            - text: :instruction[You can verify docker is ready by running the following commands in your terminal- \`docker -v\` and \`docker-compose -v\`.
                Then, from the project \`main\` directory, **run \`docker-compose up\` (or \`docker-compose up\` depending on the version of Docker you are running)** to load Anythink's backend and frontend.]{block:true}
              delay: 3000
            - text: This should take a few minutes, so hang tight. **I'll let you know when it's done.**
              delay: 1000
            - text: If you need any help, reach out to Joebroom, our Support guy, right here in Snack.
              delay: 2000
        - actionId: bot_message
          params:
            person: senior-dev
            messages:
            - text: Hi ${user.firstName} 
              delay: 2000
            - text: Welcome to our happy little ~dysfunctional~ family!
              delay: 2500
            - text: I'm Joebroom, officially transferred from "gray patterns" team to Ness's. Just wanted to introduce myself 😎
              delay: 2700
            - text: https://media.giphy.com/media/Piv9GZi2UBouyyjUxW/giphy.gif
              delay: 2700
            - text: Also, while you do have **[Discord](https://discord.gg/jcHcRB4Dzk)** to help, if things get too complicated, feel free to **:input[ask me anything]{text='My question is:'}**, and I'll try to help.
              delay: 4000
            - text: Oh, and if it's something beyond my paygrade, like a serious bug in the system, you can also **contact support@anythink.family**.
              delay: 2000
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
            - text: Umm, If you need any help, just let me know that you’re stuck.
                If that’s not the case - take your time and tell me once you're ready
                :)
              delay: 2000
