id: setup_docker_skills_selection
hints: []
startFlow:
  do:
  - actionId: bot_message
    params:
      person: head-of-rd
      messages:
        - text: "Sounds good! and :instruction[**what specific skills do you want to focus on?**] (*choose up to 3*)"
          delay: 500
        - components:
            - type: form
              form:
                id: skill_selection
                type: multi_select_form
                randomized: true
                select_limit: 3
                action_label: 'Submit Selection'
                options:
                  - value: 'Setup'
                    label: 'Setup'
                  - value: 'Observability'
                    label: 'Observability'
                  - value: 'Debugging'
                    label: 'Debugging'
                  - value: 'Communication'
                    label: 'Communication'
                  - value: 'Documentation'
                    label: 'Documentation'
                  - value: 'Git'
                    label: 'Git'
                  - value: 'Monitoring'
                    label: 'Monitoring'
                  - value: 'Operations'
                    label: 'Operations'
                  - value: 'Performance'
                    label: 'Performance'

trigger:
  type: chat_form_submitted
  params:
    formId: skill_selection
  flowNode:
    do:
    - actionId: update_user_props
      params:
        field: "onboarding.skills"
        value: "${{formSubmission}}"
    - actionId: finish_step

