id: setup_backend_docker_generic
learningObjectives:
- Setting Up Backend to run locally and connecting to DB
hints:
- Pssst - you can run `docker-compose up` from the root directory
- run `docker exec -it <container-name> sh` to access a container from the terminal.
startFlow:
  if:
    conditions:
    - conditionId: user_has_feature_flag
      params:
        featureFlag: 'codespaces'
    then:
      do:
      - actionId: bot_message
        params:
          person: head-of-rd
          messages:
          - text: Once docker-compose finishes loading up, the backend should be running and able
              to connect to the database.
            delay: 2000
          - text: "**After the server is up**, make sure you test it by **pointing your browser** to https://${user.codespace.name}-3000.githubpreview.dev/api/ping"
            delay: 1000
      - actionId: bot_message
      params:
        person: senior-dev
        messages: 
      - text: Hi ${user.firstName} welcome to our happy little ~dysfunctional~ family!  
        delay: 2000
      - text: I'm Joebroom, officially transferred from "gray patterns" team to Ness's. Just wanted to introduce myself. 
        delay: 2000
      - text: Also, while you do have **[Discord](https://discord.gg/jcHcRB4Dzk)** to help, if things get too complicated, send me a message with the problem, and I'll try to help
        delay: 2000
      - text: If it's something beyond my paygrade, like a serious bug in the system, you can also **contact support@anythink.family**
        delay: 2000
      - text: Oh, and if you have no idea what to do next, you can always tell me that you're **:input[stuck]{text='I feel stuck'}**, and I'll give you a nudge in the right direction.
        delay: 2000
    else:
      do:
      - actionId: bot_message
        params:
          person: head-of-rd
          messages:
          - text: If Docker is working correctly, the backend should be running and able
              to connect to your local database.
            delay: 2000
          - text: Let's test this by **pointing your browser** to http://localhost:3000/api/ping
            delay: 1000
            
     - actionId: bot_message
      params:
        person: senior-dev
        messages: 
      - text: Hi ${user.firstName} welcome to our happy little ~dysfunctional~ family!  
        delay: 2000
      - text: I'm Joebroom, officially transferred from "gray patterns" team to Ness's. Just wanted to introduce myself. 
        delay: 2000
      - text: Also, while you do have **[Discord](https://discord.gg/jcHcRB4Dzk)** to help, if things get too complicated, send me a message with the problem, and I'll try to help
        delay: 2000
      - text: If it's something beyond my paygrade, like a serious bug in the system, you can also **contact support@anythink.family**
        delay: 2000
      - text: Oh, and if you have no idea what to do next, you can always tell me that you're **:input[stuck]{text='I feel stuck'}**, and I'll give you a nudge in the right direction.
        delay: 2000
trigger:
  type: ping
  flowNode:
    do:
    - actionId: bot_message
      params:
        person: head-of-rd
        messages:
        - text: Easy Peasy! The backend is up and running.
          delay: 2000
     
    - actionId: finish_step
