id: setup_docker_create_codespace
hints:
  - Make sure your Codespace has started and is ready to use.
startFlow:
  if:
    conditions:
      - conditionId: user_has_feature_flag
        equals: false
        params:
          featureFlag: 'codespaces'
    then:
      do:
        - actionId: finish_step
    else:
      do:
        - actionId: bot_message
          params:
            person: head-of-rd
            messages:
              - text: "![](https://media.giphy.com/media/8fen5LSZcHQ5O/giphy.gif)"
                delay: 800
              - text: I bet you’re eager to get your hands dirty. Let’s **set up your development environment** so you can start exploring the system.
                delay:
              - text: At Anythink, our engineers work with [Github Codespaces](https://docs.github.com/en/codespaces/overview), which can be run directly in Github, so you don't need to install anything on your computer!
                delay: 2000
              - text: :Instruction[Go ahead and[ **create your own Codespace**.](https://github.com/codespaces/new?hide_repo_select=true&ref=main&repo=${user.repoId})]{block=true}
                delay: 1300
              - text: You don't need to change anything in the default options, just **click `Create Codespace` and wait a minute or two until it boots up**.
                delay: 2000
trigger:
  type: github_codespace_started
  flowNode:
    if:
      conditions:
        - conditionId: user_has_feature_flag
          params:
            featureFlag: 'codespaces'
      then:
        do:
          - actionId: bot_message
            params:
              person: head-of-rd
              messages:
                - text: Great! Looks like your codespace is up and running.
                  delay: 3000
                - text: If you need any help, just reach out to Joebroom, our Support guy, right here in Snack.
                  delay: 1000
          - actionId: bot_message
            params:
              person: senior-dev
              messages:
                - text: Hi ${user.firstName}
                  delay: 2000
                - text: Welcome to our happy little ~dysfunctional~ family!
                  delay: 2500
                - text: I'm Joebroom, officially transferred from "gray patterns" team to Ness's. Just wanted to introduce myself 😎
                  delay: 2700
                - text: https://media.giphy.com/media/Piv9GZi2UBouyyjUxW/giphy.gif
                  delay: 2700
                - text: Also, while you do have **[Discord](https://discord.gg/jcHcRB4Dzk)** to help, if things get too complicated, feel free to **:input[ask me anything]{text='My question is:'}**, and I'll try to help.
                  delay: 4000
                - text: Oh, and if it's something beyond my paygrade, like a serious bug in the system, you can also **contact support@anythink.family**.
                  delay: 2000
          - actionId: finish_step