id: setup_docker_githubsetup
learningObjectives:
  - Setting up Github
startFlow:
  do:
    - actionId: github_create_repo
  if:
    conditions:
      - conditionId: user_check_authentication_exists
        name: user_authentication
        params:
          authType: 'github'
      - conditionId: github_is_user_valid
        params:
          githubUserName: "${outputs.user_authentication.value.nickname}"
    then:
      do:
        - actionId: github_invite_user
          params:
            githubUserName: "${outputs.user_authentication.value.nickname}"
        - actionId: bot_message
          params:
            person: devops
            messages:
              - text: "Hey ${user.firstName}, I'm ${bots['devops'].displayName}, the DevOps team leader."
                delay: 2000
              - text: "I see you already have your GitHub connected, so I've added you to our GitHub org."
                delay: 1500
        - actionId: finish_step
    else:
      do:
        - actionId: bot_message
          params:
            person: devops
            messages:
              - text: "Hey ${user.firstName}"
                delay: 2000
              - text: "I'm ${bots['devops'].displayName}, the DevOps team leader."
                delay: 1500
              - text: "${bots['head-of-rd'].displayName} asked me to help you out. Just write here your :codeInstruction[**GitHub username**] and we'll add you as a contributor to the company's repository."
                delay: 2500
trigger:
  type: user_message
  params:
    person: devops
  flowNode:
    if:
      conditions:
        - conditionId: github_is_user_valid
          params:
            githubUserName: "${userMessageText}"
      then:
        do:
          - actionId: github_invite_user
            params:
              githubUserName: "${userMessageText}"
          - actionId: bot_message
            params:
              person: devops
              messages:
                - text: "Good, I've added you to our GitHub org."
                  delay: 1500
          - actionId: finish_step
      else:
        do:
          - actionId: bot_message
            params:
              person: devops
              messages:
                - text: "I mean, I get it, it's your first day here and everything, so let's try again - because Github says that the username \"${userMessageText}\" doesn't exist."
                  delay: 1800
                - text: "Can you check again and send me your **CORRECT Github username?**"
                  delay: 2000